#requires -Version 7.0
# steps/70-git-identity.ps1 — per-workspace git identity via git includeIf.
#
# We never touch the user's global user.name / user.email. Instead we add
# a single `[includeIf "gitdir:<workspace>/"]` block that points at a
# workspace-local .gitconfig containing the work identity. Personal repos
# outside the workspace continue to use the original global identity.

function Get-CABGlobalGitconfigPath {
    if ($IsWindows) { return Join-Path $env:USERPROFILE '.gitconfig' }
    return Join-Path $HOME '.gitconfig'
}

# Normalize a workspace path into the form git's gitdir matcher expects:
#   - forward slashes on every platform
#   - trailing slash present (matches the directory, not files prefixed with it)
function ConvertTo-CABGitdirPattern {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$Path)
    $p = $Path.Replace('\','/')
    if (-not $p.EndsWith('/')) { $p += '/' }
    return $p
}

function Test-CABStep70 {
    [CmdletBinding()]
    param([hashtable]$Context)
    if (-not $Context.WorkspacePath) {
        return @{ status = 'fail'; details = 'Workspace not set.' }
    }
    $globalPath = Get-CABGlobalGitconfigPath
    if (-not (Test-Path $globalPath)) {
        return @{ status = 'pending'; details = 'No global .gitconfig — will create includeIf entry.' }
    }
    $content = Get-Content -Raw -Path $globalPath
    $pattern = ConvertTo-CABGitdirPattern -Path $Context.WorkspacePath
    $needle = "gitdir:$pattern"
    if ($content -like "*$needle*") {
        return @{ status = 'ok'; details = 'includeIf for this workspace is already configured.' }
    }
    return @{ status = 'pending'; details = 'No includeIf for this workspace yet.' }
}

function Invoke-CABStep70 {
    [CmdletBinding()]
    param([hashtable]$Context)

    Write-CABStep -Number 7 -Total $Context.TotalSteps -Title 'Git identity for ChannelAssist'

    if (-not $Context.WorkspacePath) {
        return @{ status = 'fail'; details = 'Workspace not set.' }
    }

    $detection = Test-CABStep70 -Context $Context
    if ($detection.status -eq 'ok') {
        return @{ status = 'skip'; details = $detection.details }
    }

    $currentName  = (& git config --global user.name  2>$null) -join ''
    $currentEmail = (& git config --global user.email 2>$null) -join ''

    if ($currentName -or $currentEmail) {
        Write-Host "  Detected global git identity: $currentName <$currentEmail>"
    } else {
        Write-Host '  No global git identity is set yet.'
    }
    Write-Host ''
    Write-Host '  ChannelAssist repos should commit with your work email. The setup'
    Write-Host "  will add an includeIf block to your global .gitconfig that scopes"
    Write-Host "  the work identity to $($Context.WorkspacePath)."
    Write-Host '  Personal repos outside that path keep your existing identity.'
    Write-Host ''

    $proceed = Read-CABConfirm -Question 'Configure ChannelAssist-specific identity?' -Default $true -AnswerKey 'identity.configure'
    if ($proceed -is [string] -and $proceed -eq 'quit') {
        return @{ status = 'quit'; details = 'User quit at identity step.' }
    }
    if ($proceed -is [bool] -and -not $proceed) {
        return @{ status = 'skip'; details = 'User skipped identity configuration.' }
    }

    # Prompts for name and email.
    Write-Host "  Name for ChannelAssist commits [$currentName]: " -NoNewline
    $name = if ($Context.Unattended) { '' } else { Read-Host }
    if ([string]::IsNullOrWhiteSpace($name)) { $name = $currentName }

    Write-Host "  Email for ChannelAssist commits: " -NoNewline
    $email = if ($Context.Unattended) { '' } else { Read-Host }
    if ([string]::IsNullOrWhiteSpace($email)) {
        # No reasonable default — work email isn't derivable. Fail clearly.
        return @{ status = 'fail'; details = 'Email is required (no default available — please re-run and provide your work email).' }
    }
    if ([string]::IsNullOrWhiteSpace($name)) {
        return @{ status = 'fail'; details = 'Name is required.' }
    }

    if ($Context.WhatIfMode) {
        Write-CABStatus -Status info -Message "WhatIf: would write workspace .gitconfig with $name <$email> and add includeIf to $(Get-CABGlobalGitconfigPath)"
        return @{ status = 'ok'; details = 'WhatIf: identity changes simulated.' }
    }

    # Write the workspace .gitconfig.
    $workspaceGitconfig = Join-Path $Context.WorkspacePath '.gitconfig'
    $workspaceContent = @"
# ChannelAssist developer identity for this workspace.
# Generated by ca-bootstrap. Edit freely; ca-bootstrap re-runs are
# idempotent and won't overwrite your changes.
[user]
    name = $name
    email = $email
"@
    Set-Content -Path $workspaceGitconfig -Value $workspaceContent

    # Append includeIf to the global gitconfig.
    $globalPath = Get-CABGlobalGitconfigPath
    $pattern = ConvertTo-CABGitdirPattern -Path $Context.WorkspacePath
    $includeBlock = @"

# Added by ca-bootstrap — scopes the ChannelAssist identity to the workspace.
[includeIf "gitdir:$pattern"]
    path = $workspaceGitconfig
"@
    if (-not (Test-Path $globalPath)) {
        Set-Content -Path $globalPath -Value $includeBlock.TrimStart()
    } else {
        Add-Content -Path $globalPath -Value $includeBlock
    }

    Add-CABJournalEntry -Step '70-git-identity' -Action 'configure_git_identity' -Data @{
        workspace                 = $Context.WorkspacePath
        global_gitconfig_path     = $globalPath
        workspace_gitconfig_path  = $workspaceGitconfig
        previous_global_email     = $currentEmail
        previous_global_name      = $currentName
        new_workspace_email       = $email
        new_workspace_name        = $name
    } | Out-Null

    return @{ status = 'ok'; details = "Identity scoped to $($Context.WorkspacePath): $name <$email>" }
}

function Undo-CABStep70 {
    @{ status = 'noop'; details = 'Reversed by undo: removes includeIf block + workspace .gitconfig.' }
}
